### ISSUE TITLE
Error while creating new user after updating marzban to v0.5.0

### ISSUE THREAD

**Issue by sephrrr** [mewhrzad/marzpy#18]
`TypeError: __init__() got an unexpected keyword argument 'auto_delete_in_days'`

marzypy shows this error after i have recently updated marzban to latest version 0.5.0

`async def add_user(username, expire, data_limit):
    panel = Marzban('user', 'user', 'url')
    token = await panel.get_token()

    generate_new_uuid = generate_uuid()

    user = User(
        username=username,
        proxies={
            "vless": {"id": generate_new_uuid}
        },
        inbounds={},
        expire=None,
        data_limit=data_limit,
        data_limit_reset_strategy="no_reset",
        status="on_hold",
        on_hold_expire_duration=(86400 * int(expire))
    )
    result = await panel.add_user(user=user, token=token)  # return new User object
    return result`
